# Generated by Django 4.1.5 on 2023-01-23 12:33

import atv.models.atividade
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associacao',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('alias', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Apelido')),
            ],
            options={
                'verbose_name': 'Associação',
                'verbose_name_plural': 'Associações',
            },
        ),
        migrations.CreateModel(
            name='GrupoEscoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('region', models.CharField(max_length=20, verbose_name='Região')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atv.associacao')),
            ],
        ),
        migrations.CreateModel(
            name='Escotista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('external_id', models.CharField(max_length=16, verbose_name='Id')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atv.associacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('ramos', multiselectfield.db.fields.MultiSelectField(choices=[('L', 'Lobinho'), ('E', 'Escoteiro'), ('S', 'Sênior'), ('P', 'Pioneiro')], max_length=7, validators=[atv.models.atividade.validate_ramos], verbose_name='Ramos')),
                ('enfases', multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Física'), ('I', 'Intelectual'), ('C', 'Caráter'), ('A', 'Afetividade'), ('S', 'Social'), ('E', 'Espiritual')], max_length=11, verbose_name='Ênfases')),
                ('autor_url', models.URLField(null=True, verbose_name='URL Autor')),
                ('descricao', martor.models.MartorField(verbose_name='Descrição')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
