# Generated by Django 4.1.5 on 2023-01-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0001_initial'),
    ]

    operations = [
    ]
