# Generated by Django 4.1.5 on 2023-01-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0002_auto_20230129_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escotista',
            name='email',
        ),
        migrations.AddField(
            model_name='escotista',
            name='scout_group',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, to='atv.grupoescoteiro'),
            preserve_default=False,
        ),
    ]
