# Generated by Django 4.1.5 on 2023-01-29 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atv', '0003_remove_escotista_email_escotista_scout_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escotista',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
