# Generated by Django 4.1.5 on 2023-02-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0004_alter_escotista_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='escotista',
            name='subscribe_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data do cadastro'),
        ),
    ]
