# Generated by Django 4.1.5 on 2023-02-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0005_escotista_subscribe_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de criação'),
        ),
    ]
