# Generated by Django 4.1.5 on 2023-02-01 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0007_atividade_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atv.escotista'),
        ),
    ]
